name: Deploy do Portfolio

on:
  push:
    branches:
      - main # Ou master, caso use o nome antigo

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Instalar Node.js ⚙️
        uses: actions/configure-pages@v4
        uses: actions/setup-node@v4
        with:
          node-node-version: 20
          cache: 'npm'

      - name: Instalar e Buildar 🚀
        run: |
          npm install
          npm run build

      - name: Deploy no GitHub Pages 📂
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta gerada pelo Vite
          branch: gh-pages # Branch onde o GitHub Pages lerá os arquivos compilados
